---
- name: Stopping Package Kit
  ignore_errors: yes
  become: yes
  become_method: sudo
  ansible.builtin.command: systemctl stop packagekit
- name: Installing Git2.27
  ignore_errors: yes
  become: yes
  become_method: sudo
  yum:
    name: rh-git227
  environment:
    http_proxy: http://contractorproxyeast.northgrum.com:80
    https_proxy: https://contractorproxyeast.northgrum.com:80
